workflows:
  python_app:
    name: Build & Test Python App (API + Admin + Bot)
    max_build_duration: 60
    environment:
      vars:
        PYTHONUNBUFFERED: "1"
    scripts:
      - name: Set up Python
        script: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          python3 --version
          pip3 --version

      - name: Install dependencies
        script: |
          if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi

      - name: Run migrations (if Django/Flask with DB)
        script: |
          if [ -f manage.py ]; then python3 manage.py migrate; fi

      - name: Test backend start
        script: |
          if [ -f main.py ]; then python3 main.py --help || true; fi

      - name: Test telegram bot start
        script: |
          if [ -f bot_working_fixed.py ]; then python3 bot_working_fixed.py --help || true; fi

    artifacts:
      - "**/*.py"
      - "**/*.log"
      - "**/*.md"

    publishing:
      scripts:
        - echo "✅ Build finished. Python API + Admin + Telegram Bot ready."
